# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

#future: false

title:               'Math Salad'
tagline:             'Incoherent mathematical writings'
email: 'corrections_comments@mathsalad.com'

#description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
#url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
# About/contact
author:              Paul Plummer
name:              Paul Plummer
#  url:               https://twitter.com/mdo


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Paul Plummer"
      
      

markdown: kramdown

collections:
 - blogroll
 
# Custom vars
#version:             test site
