# Site settings
title: Math Salad
#email: your-email@domain.com
description: "A site of incorherent mathematical rambling."
baseurl: ""
#url: "http://yourdomain.com"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
